
import { HandoverData } from "./handover";
import { GovernanceEntry } from "./governance";

/**
 * Synthesizes a comprehensive clinical bundle for clinician review.
 */
export function generateClinicalExportBundle(handover: HandoverData, logs: GovernanceEntry[]): string {
  const timestamp = new Date().toLocaleString();
  
  let output = `PEDIPULSE CLINICAL BUNDLE - Generated: ${timestamp}\n`;
  output += `====================================================\n\n`;
  
  output += `PART 1: ISBAR HANDOVER SUMMARY\n`;
  output += `------------------------------\n`;
  output += `ID: ${handover.identification.name} | DOB: ${handover.identification.dob} | Wt: ${handover.identification.weight}\n`;
  output += `Situation: ${handover.situation.activeIssues.join(', ') || 'No active issues recorded'}\n`;
  output += `Background: ${handover.background.pastMedicalHistory}\n`;
  output += `Allergies: ${handover.background.allergies.join(', ') || 'None reported'}\n`;
  output += `Meds: ${handover.background.medications.join(', ') || 'None active'}\n\n`;

  output += `PART 2: DECISION GOVERNANCE LOG (Audit Trail)\n`;
  output += `-------------------------------------------\n`;
  if (logs.length === 0) {
    output += `No decision support events recorded in the current session.\n`;
  } else {
    logs.slice(0, 10).forEach(entry => {
      output += `[${entry.timestamp}] Event: ${entry.eventType}\n`;
      output += `  Rationale: ${entry.inputSummary}\n`;
      output += `  Red Flags: ${entry.redFlags?.join(', ') || 'None'}\n`;
      output += `  Mode: ${entry.userRole} (${entry.environment})\n`;
      output += `  Connectivity: ${entry.online ? 'Online' : 'Offline'}\n\n`;
    });
  }

  output += `\n*** REGULATORY DISCLOSURE ***\n`;
  output += `This document was generated by PediPulse AI, a decision-support tool. It is for information purposes only and does not replace professional clinical judgment. Clinical decisions remain the responsibility of the healthcare provider.\n`;

  return output;
}
